### PR TITLE
Add support for percent sign parsing

### PR DESCRIPTION
**Pull request by niksy**
In browsers with native support, percent sign is properly parsed, but there is no parse support in this polyfill. This PR adds that functionality based on [StackOverflow suggestion](https://stackoverflow.com/a/54310080).

### CODE REVIEW

**Comment by WebReflection** [comment]
interesting, but I have two things to ask/say:

  * the `findPercentSign.lastIndex = 0;` is useless with `g`, as every time the replace would consume all of it, so no need to reset the index, as it's not needed for `find` neither
  * if the browser doesn't do that natively, it should use the polyfilled version, so the test should be performed in the initial try/catch too

thoughts?

**Comment by niksy** [comment]
* Sure, `lastIndex` reset removed!
* I’ve tried it in latest Chrome, Firefox and [Node REPL](https://repl.it/@niksy/URLSearchParams-percent-encoding) and it works as it should. I can add that check to initial try/catch just to be sure, but this seems like per-spec implementation.

**Comment by WebReflection** [comment]
[all these checks](https://github.com/ungap/url-search-params/blob/master/index.js#L6-L10) find out browsers that badly implemented specs, which is why I think another check for this should be needed just in case.

**Comment by niksy** [comment]
Done!

**Comment by WebReflection** [comment]
Published, thank you!

**Pull request merged**
